### ISSUE TITLE
BEAM dashboard uses hardcoded Prometheus datasource

### ISSUE THREAD

**Issue by tsloughter** [deadtrickster/beam-dashboards#5]
The BEAM dashboard is using the hardcoded `Prometheus` datasource name while Elli dashboard uses the input `${DS_PROMETHEUS}`.

Should BEAM also use the input?

I'm working on automating the deployment of these dashboards with my systems and trying to make these names configurable/templated.

**Comment by deadtrickster** [comment]
closed in #6.
